# Generated by Django 5.2 on 2025-04-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_budget'),
        ('accounts', '0004_create_default_categories'),
    ]

    operations = [
    ]
